function TermsOfUse() {  
  return (
    <>
      <div className="pagePadding"> <br />
        <h3 className="subHeading"> Terms of service </h3>

        <section className="termsOfUse">
          <p>
            <br />
            These terms and conditions govern your use of the e-commerce website
            named Ecoyaan.com, accessible at https://Ecoyaan.com and the
            corresponding mobile application, Ecoyaan, collectively referred to
            as the ‘Platform’. Ecoyaan is a brand owned, operated, and managed
            by Kindkarma E-Retail Private Limited, a company duly incorporated
            under the provisions of the Companies Act, 1956 and having its
            registered office at 1-N-12T-781/1, Sri Krishna Vilasa, Urvastores,
            Ashoknagar (MR), Mangalore, Dakshina Kannada, Karnataka hereinafter
            collectively referred to as the (“Company,” “Us,” “We,” “Ecoyaan”).
            <br />
            By accessing or visiting this website or using the Platform, you
            acknowledge that you have read, understood, and agree to be lawfully
            bound by the contents of these terms & conditions. Except as
            otherwise specified, these terms and conditions do not apply to
            third-party products or services, which shall be governed by their
            own terms of service. This document is an electronic record in terms
            of the Information Technology Act, 2000 and rules made thereunder.
            Further, this electronic record is generated by a computer system
            and does not require any physical or digital signatures. This
            electronic record is published in accordance with the relevant
            provisions of the Information Technology Act, 2000, and rules made
            thereunder.
          </p>
          <br />
          <p>
            If you disagree with these terms and conditions or any part of these
            terms and conditions, you must not use this website.
            <br />
            You must be at least 18 years of age to use this website. By using
            this website and by agreeing to these terms and conditions you
            warrant and represent that you are at least 18 years of age.
          </p>
          <br />
          <p>
            This website uses cookies. By using this website and agreeing to
            these terms and conditions, you consent to our Ecoyaan’s use of
            cookies in accordance with the terms of Ecoyaan’s privacy
            policy/cookies policy.
          </p>
          <br />

          <h2 className="subHeading">License To Use Website:</h2>
          <br />
          <ul className="list-disc list-inside m-2">
            <li>
              Unless otherwise stated, Ecoyaan and/or its licensors own the
              intellectual property rights in the website and material on the
              website. Subject to the license below, all these intellectual
              property rights are reserved.
            </li>
            <li>
              You may view, download for caching purposes only, and print pages
              [or [OTHER CONTENT]] from the website for your own personal use,
              subject to the restrictions set out below and elsewhere in these
              terms and conditions.{" "}
            </li>
            <li>
              You must NOT republish material from this website (including
              republication on another website);
            </li>
            <li>
              You must NOT sell, rent or sub-license material from the website;
            </li>
            <li>You must NOT show any material from the website in public;</li>
            <li>
              You must NOT reproduce, duplicate, copy or otherwise exploit
              material on this website for a commercial purpose;
            </li>
            <li>
              You must NOT edit or otherwise modify any material on the website;
              or
            </li>
            <li>
              You must NOT redistribute material from this website [except for
              content specifically and expressly made available for
              redistribution.
            </li>
          </ul>

          <br />
          <h2 className="subHeading">Acceptable Use:</h2>
          <br />
          <ul className="list-disc list-inside m-2">
            <li>
              You must NOT use this website in any way that causes, or may
              cause, damage to the website or impairment of the availability or
              accessibility of the website; or in any way which is unlawful,
              illegal, fraudulent or harmful, or in connection with any
              unlawful, illegal, fraudulent or harmful purpose or activity.
            </li>
            <li>
              You must NOT use this website to copy, store, host, transmit,
              send, use, publish or distribute any material which consists of
              (or is linked to) any spyware, computer virus, Trojan horse, worm,
              keystroke logger, rootkit or other malicious computer software.
            </li>
            <li>
              You must NOT conduct any systematic or automated data collection
              activities (including without limitation scraping, data mining,
              data extraction and data harvesting) on or in relation to this
              website without Ecoyaan’s express written consent.
            </li>
            <li>
              You must NOT use this website to transmit or send unsolicited
              commercial communications.
            </li>
            <li>
              You must not use this website for any purposes related to
              marketing without Ecoyaan’s express written consent.
            </li>
          </ul>

          <br />
          <h2 className="subHeading">Restricted Access:</h2>
          <br />
          <ul className="list-disc list-inside m-2">
            <li>
              Access to certain areas of this website is restricted. Ecoyaan
              reserves the right to restrict access to other areas of this
              website, or indeed this entire website, at Ecoyaan’s discretion.
            </li>
            <li>
              If Ecoyaan provides you with a user ID and password to enable you
              to access restricted areas of this website or other content or
              services, you must ensure that the user ID and password are kept
              confidential.{" "}
            </li>
            <li>
              Ecoyaan may disable your user ID and password in Ecoyaan’s sole
              discretion without notice or explanation.
            </li>
          </ul>

          <br />
          <h2 className="subHeading">User Content:</h2>
          <br />
          <p>
            In these terms and conditions, “your user content” means material
            (including without limitation text, images, audio material, video
            material and audio-visual material) that you submit to this website,
            for whatever purpose.
          </p>
          <br />
          <ul className="list-disc list-inside m-2">
            <li>
              You grant to Ecoyaan a worldwide, irrevocable, non-exclusive,
              royalty-free license to use, reproduce, adapt, publish, translate
              and distribute your user content in any existing or future media.
              You also grant to Ecoyaan the right to sub-license these rights,
              and the right to bring an action for infringement of these rights
            </li>
            <li>
              Your user content must not be illegal or unlawful, must not
              infringe any third party's legal rights, and must not be capable
              of giving rise to legal action whether against you or Ecoyaan or a
              third party (in each case under any applicable law).{" "}
            </li>
            <li>
              You must not submit any user content to the website that is or has
              ever been the subject of any threatened or actual legal
              proceedings or other similar complaints.
            </li>
            <li>
              You must not submit any user content to the website that is or has
              ever been the subject of any threatened or actual legal
              proceedings or other similar complaints.
            </li>
            <li>
              Notwithstanding Ecoyaan’s rights under these terms and conditions
              in relation to user content, Ecoyaan does not undertake to monitor
              the submission of such content to, or the publication of such
              content on, this website.
            </li>
          </ul>

          <br />
          <h2 className="subHeading">No Warranties:</h2>
          <br />
          <p>
            This website is provided “as is” without any representations or
            warranties, express or implied. Ecoyaan makes no representations or
            warranties in relation to this website or the information and
            materials provided on this website.{" "}
          </p>
          <br />
          <p>
            Without prejudice to the generality of the foregoing paragraph,
            Ecoyaan does not warrant that:{" "}
          </p>
          <br />
          <ul className="list-disc list-inside m-2">
            <li>
              Without prejudice to the generality of the foregoing paragraph,
              Ecoyaan does not warrant that:{" "}
            </li>
            <li>
              The information on this website is complete, true, accurate or
              non-misleading.
            </li>
          </ul>
          <br />
          <p>
            Nothing on this website constitutes or is meant to constitute,
            advice of any kind. If you require advice in relation to any [legal,
            financial or medical] matter you should consult an appropriate
            professional.
          </p>

          <br />
          <h2 className="subHeading">Limitations of Liability:</h2>
          <br />
          <p>
            Ecoyaan will not be liable to you (whether under the law of
            contract, the law of torts or otherwise) in relation to the contents
            of, or use of, or otherwise in connection with, this website:{" "}
          </p>
          <br />
          <ul className="list-disc list-inside m-2">
            <li>
              To the extent that the website is provided free-of-charge, for any
              direct loss;
            </li>
            <li>For any indirect, special or consequential loss; or</li>
            <li>
              For any business losses, loss of revenue, income, profits or
              anticipated savings, loss of contracts or business relationships,
              loss of reputation or goodwill, or loss or corruption of
              information or data.
            </li>
          </ul>
          <br />
          <p>
            These limitations of liability apply even if Ecoyaan has been
            expressly advised of the potential loss.
          </p>

          <br />
          <h2 className="subHeading">Exceptions:</h2>
          <br />
          <p>
            Nothing in this website disclaimer will exclude or limit any
            warranty implied by law that it would be unlawful to exclude or
            limit, and nothing in this website disclaimer will exclude or limit
            Ecoyaan’s liability in respect of any:{" "}
          </p>
          <br />
          <ul className="list-disc list-inside m-2">
            <li>Death or personal injury caused by Ecoyaan’s negligence;</li>
            <li>
              Fraud or fraudulent misrepresentation on the part of Ecoyaan; or
            </li>
            <li>
              A matter which it would be illegal or unlawful for Ecoyaan to
              exclude or limit, or to attempt or purport to exclude or limit,
              its liability.
            </li>
          </ul>

          <br />
          <h2 className="subHeading">Reasonableness:</h2>
          <br />
          <p>
            By using this website, you agree that the exclusions and limitations
            of liability set out in this website disclaimer are reasonable.{" "}
          </p>
          <br />
          <p>
            If you do not think they are reasonable, you must not use this
            website.
          </p>

          <br />
          <h2 className="subHeading">Other Parties:</h2>
          <br />
          <p>
            You accept that, as a limited liability / private limited entity,
            Ecoyaan has an interest in limiting the personal liability of its
            officers, shareholders, directors and employees. You agree that you
            will not bring any claim personally against Ecoyaan’s officers,
            shareholders, directors or employees in respect of any losses you
            suffer in connection with the website.
          </p>
          <br />
          <p>
            Without prejudice to the foregoing paragraph, you agree that the
            limitations of warranties and liability set out in this website
            disclaimer will protect Ecoyaan’s officers, employees, shareholders,
            directors, agents, subsidiaries, successors, assigns and
            sub-contractors as well as Ecoyaan.
          </p>

          <br />
          <h2 className="subHeading">Unenforceable Provisions:</h2>
          <br />
          <p>
            If any provision of this website disclaimer is or is found to be,
            unenforceable under applicable law, that will not affect the
            enforceability of the other provisions of this website disclaimer.
          </p>

          <br />
          <h2 className="subHeading">Indemnity:</h2>
          <br />
          <p>
            You hereby indemnify Ecoyaan and undertake to keep Ecoyaan
            indemnified against any losses, damages, costs, liabilities and
            expenses (including without limitation legal expenses and any
            amounts paid by Ecoyaan to a third party in settlement of a claim or
            dispute on the advice of Ecoyaan’s legal advisers) incurred or
            suffered by Ecoyaan arising out of any breach by you of any
            provision of these terms and conditions, or arising out of any claim
            that you have breached any provision of these terms and conditions.
          </p>

          <br />
          <h2 className="subHeading">
            Breaches of these Terms And Conditions:
          </h2>
          <br />
          <p>
            Without prejudice to Ecoyaan’s other rights under these terms and
            conditions, if you breach these terms and conditions in any way,
            Ecoyaan may take such action as Ecoyaan deems appropriate to deal
            with the breach, including suspending your access to the website,
            prohibiting you from accessing the website, blocking computers using
            your IP address from accessing the website, contacting your internet
            service provider to request that they block your access to the
            website and/or bringing court proceedings against you and/or
            claiming compensation in case of any losses suffered by Ecoyaan,
            under the provisions of these terms and conditions of usage of its
            website.
          </p>

          <br />
          <h2 className="subHeading">Variation:</h2>
          <br />
          <p>
            Ecoyaan may revise these terms and conditions from time-to-time.
            Revised terms and conditions will apply to the use of this website
            from the date of the publication of the revised terms and conditions
            on this website. Please check this page regularly to ensure you are
            familiar with the current version.
          </p>

          <br />
          <h2 className="subHeading">Variation:</h2>
          <br />
          <p>
            Ecoyaan may revise these terms and conditions from time-to-time.
            Revised terms and conditions will apply to the use of this website
            from the date of the publication of the revised terms and conditions
            on this website. Please check this page regularly to ensure you are
            familiar with the current version.
          </p>

          <br />
          <h2 className="subHeading">Assignment:</h2>
          <br />
          <p>
            Ecoyaan may transfer, sub-contract or otherwise deal with Ecoyaan’s
            rights and/or obligations under these terms and conditions without
            notifying you or obtaining your consent.
          </p>

          <br />

          <p>
            You may not transfer, sub-contract or otherwise deal with your
            rights and/or obligations under these terms and conditions.{" "}
          </p>

          <br />
          <h2 className="subHeading">Severability:</h2>
          <br />
          <p>
            If a provision of these terms and conditions is determined by any
            court or other competent authority to be unlawful and/or
            unenforceable, the other provisions will continue in effect. If any
            unlawful and/or unenforceable provision would be lawful or
            enforceable if part of it were deleted, that part will be deemed to
            be deleted, and the rest of the provision will continue in effect.{" "}
          </p>

          <br />
          <h2 className="subHeading">Entire Agreement:</h2>
          <br />
          <p>
            These terms and conditions, together with documents, constitute the
            entire agreement between you and Ecoyaan in relation to your use of
            this website and supersede all previous agreements in respect of
            your use of this website.
          </p>

          <br />
          <h2 className="subHeading">Law And Jurisdiction:</h2>
          <br />
          <p>
            These terms and conditions will be governed by and construed in
            accordance with competent courts under the jurisdiction of
            Mangalore, Karnataka, and any disputes relating to the
            interpretation of understanding of these terms and conditions will
            be subject to the exclusive jurisdiction of the Court of Law of
            Mangalore, Karnataka.
          </p>
        </section>
      </div>
      <div className="spacer bg-color"></div>
    </>
  );
}

export default TermsOfUse;
