import { PackagingType, ProductType } from "../enums/ProductEnums";
import { Product } from "./product";

export const productstest: Product[] = [
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
  {
    id: 0,
    name: "Bare Neccessity",
    description: "Bare Necessity Desc",
    content: "",
    type: ProductType.GOODS,
    net_weight: 100,
    volumetric_weight: 200,
    sku: "A",
    upc: "B",
    ean: "C",
    mpn: "B",
    packaging_type: PackagingType.CARDBOARD,
    green_rating: 0,
    product_gallery: [
      {
        id: 0,
        productFk: 0,
        resource:
          "https://m.media-amazon.com/images/I/71QaJBTeMrL._AC_UL320_.jpg",
        description: "Image Description",
      },
    ],
    product_details: [
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "VEGAN",
      },
      {
        id: 0,
        product_fk: 0,
        attribute: "",
        value: "SUSTAINABLE",
      },
    ],
  },
];
